### ISSUE TITLE
---- Minecraft Crash Report ----

### ISSUE THREAD

**Issue by Mrkele** [randombyte-developer/unity#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (【P】[前置]spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 18-4-20 下午9:46
Description: Watching Server

java.lang.Error
	at java.util.zip.ZipFile.getEntry(Native Method)
	at java.util.zip.ZipFile.getEntry(Unknown Source)
	at java.util.jar.JarFile.getEntry(Unknown Source)
	at java.util.jar.JarFile.getJarEntry(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.findResource(Unknown Source)
	at sun.misc.URLClassPath.findResource(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findCodeSourceConnectionFor(LaunchClassLoader.java:255)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:138)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at io.github.nucleuspowered.nucleus.dataservices.modular.ModularGeneralService.tryGetTransient(ModularGeneralService.java:23)
	at io.github.nucleuspowered.nucleus.dataservices.modular.ModularDataService.getTransient(ModularDataService.java:47)
	at io.github.nucleuspowered.nucleus.NucleusPlugin.onGameStarting(NucleusPlugin.java:473)
	at org.spongepowered.common.event.listener.GameStartingServerEventListener_NucleusPlugin_onGameStarting28.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:371)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213)
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:771)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:296)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:306)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by randombyte-developer** [comment]
Sponge version? Forge version? When does this happen? Please post a full server log to pastebin.com.

It seems that nucleus is causing this crash. Try removing nucleus and check if the crash happens again.

**Comment by randombyte-developer** [comment]
Closed due to inactivity
