### ISSUE TITLE
Updating to 3291 causes errors on startup and player login

### ISSUE THREAD

**Issue by Rasgnarok** [randombyte-developer/unity#7]
`[00:31:00] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartingEvent to Plugin{id=unity, name=Unity, version=2.2.1, authors=[RandomByte], source=./mods/unity-2.2.1.jar}
org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:89) ~[AbstractDataBuilder.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.common.data.SpongeDataManager.lambda$deserialize$1(SpongeDataManager.java:198) ~[SpongeDataManager.class:1.12.2-2705-7.1.0-BETA-3291]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_171]
	at org.spongepowered.common.data.SpongeDataManager.deserialize(SpongeDataManager.java:198) ~[SpongeDataManager.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:50) ~[DataSerializableTypeSerializer.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:94) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:268) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:235) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.deserialize(TypeSerializers.java:219) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:94) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:268) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:211) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:491) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3291.jar:1.12.2-2705-7.1.0-BETA-3291]
	at de.randombyte.unity.shaded.kosp.config.ConfigManager.get(ConfigManager.kt:48) ~[ConfigManager.class:?]
	at de.randombyte.unity.Unity.loadConfig(Unity.kt:219) ~[Unity.class:?]
	at de.randombyte.unity.Unity.onWorldsLoaded(Unity.kt:112) ~[Unity.class:?]
	at org.spongepowered.common.event.listener.GameStartingServerEventListener_Unity_onWorldsLoaded70.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:233) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:267) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3291]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:794) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:296) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:306) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.spongepowered.api.data.persistence.InvalidDataException: Could not find world by UUID: 090ea47f-3fc2-477e-907f-e1c9e662cf58
	at org.spongepowered.common.data.builder.world.LocationBuilder.buildContent(LocationBuilder.java:57) ~[LocationBuilder.class:1.12.2-2705-7.1.0-BETA-3291]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87) ~[AbstractDataBuilder.class:1.12.2-2705-7.1.0-BETA-3291]
	... 56 more`

and

`[03:12:31] [Server thread/ERROR] [Sponge]: Could not pass InteractEntityEvent$Secondary$MainHand$Impl to Plugin{id=unity, name=Unity, version=2.2.1, authors=[RandomByte], source=./mods/unity-2.2.1.jar}
de.randombyte.unity.shaded.kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
        at de.randombyte.unity.Unity.onKissPartner(Unity.kt:145) ~[Unity.class:?]
        at org.spongepowered.common.event.listener.MainHandListener_Unity_onKissPartner71.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:360) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:416) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:227) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3291]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractEntityEventSecondary(SpongeCommonEventFactory.java:748) [SpongeCommonEventFactory.class:1.12.2-2705-7.1.0-BETA-3291]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2542) [pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3291]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlc000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:288) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3291]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjh000(MinecraftServer.java:3987) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**Comment by randombyte-developer** [comment]
The second error results from the first one. Please post the whole server log and your config to https://hastebin.com

Also your Forge and Sponge version.

**Comment by Rasgnarok** [comment]
Says it in the title and error, I am running SF 3291. Forge is obviously to 2705, wouldn't load otherwise. Server log is huge, that's the only of Unity in there, but I can still show it to you, compressed, if it is a non-error.

I'll get you the config shortly.

**Comment by randombyte-developer** [comment]
I suspect changes in how Sponge serializes `Location`s, these are needed for the homes of a couple. But first I will check the config when it's there.

**Comment by Rasgnarok** [comment]
Here's the config for Unity - I'll be testing that beta build in a bit, first trying to diagnose why End/Nether won't load on default configs.
[unity.zip](https://github.com/randombyte-developer/unity/files/2186118/unity.zip)

**Comment by randombyte-developer** [comment]
The log you sent on the Sponge Discord doesn't have any `InvalidDataException` anymore. Do the homes work ingame?

**Comment by randombyte-developer** [comment]
This was resolved two versions back.
